name: Build and publish preview release

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline --ignore-scripts

      - name: Build
        run: pnpm prep

      - name: Type check
        run: pnpm check

      - name: Format check
        run: pnpm format:check

      - name: Publish preview release
        run: pnpm pkg-pr-new publish --no-template
